//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaacademico_vs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asignatura()
        {
            this.matricula = new HashSet<matricula>();
        }
    
        public int id_asignatura { get; set; }
        public string nombre { get; set; }
        public string profesor { get; set; }
        public int creditos { get; set; }
        public string duracion { get; set; }
        public int id_notas { get; set; }
    
        public virtual notas notas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula> matricula { get; set; }
    }
}
