//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaacademico_vs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notas()
        {
            this.asignatura = new HashSet<asignatura>();
        }
    
        public int id_nota { get; set; }
        public double nota_1 { get; set; }
        public double nota_2 { get; set; }
        public double nota_definitiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignatura> asignatura { get; set; }
    }
}
